apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /api/employees
            pathType: Prefix
            backend:
              service:
                name: employee-service
                port:
                  number: 80
